- name: Deploy Caddy Web Server
  gather_facts: false
  hosts: all
  become: true

  tasks:
    - name: Install Firewalld
      ansible.builtin.dnf:
        name: firewalld
    - name: Enable Firewalld
      ansible.builtin.systemd_service:
        name: firewalld
        state: started
        enabled: true
    - name: Allow HTTP
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
    - name: Allow HTTPS
      ansible.posix.firewalld:
        service: https
        permanent: true
        state: enabled
        immediate: true
    - name: Create Caddy config path
      ansible.builtin.file:
        path: /etc/caddy
        state: directory
    - name: Create Caddy sites path
      ansible.builtin.file:
        path: /etc/caddy/sites
        state: directory
    - name: Create main caddy config
      ansible.builtin.copy:
        dest: /etc/caddy/Caddyfile
        force: true
        content: |
          {
            admin off
            local_certs
            skip_install_trust
            auto_https disable_redirects 
            default_bind fd/4 {
              protocols h1 h2
            }
            default_bind fdgram/5 {
              protocols h3
            }
          }

          (binding) {
          }

          http:// {
            bind fd/3 {
              protocols h1
            }
            redir https://{host}{uri}
          }
 
          import sites/*
    - name: Create network file
      ansible.builtin.copy:
        dest: /etc/containers/systemd/caddy.network
        content: |
          [Network]
          Subnet=100.80.0.0/24
          Gateway=100.80.0.1
    - name: Create socket file
      ansible.builtin.copy:
        dest: /etc/systemd/system/caddy.socket
        content: |
          [Unit]
          Description=Caddy Socket

          [Socket]
          ListenStream=80
          ListenStream=443
          ListenDatagram=443
          BindIPv6Only=both
          NoDelay=true
          DeferAcceptSec=5
          ReusePort=true
          Timestamping=us
          TCPCongestion=bbr

          [Install]
          WantedBy=default.target
    - name: Create caddy_data volume file
      ansible.builtin.copy:
        dest: /etc/containers/systemd/caddy_data.volume
        content: |
          [Volume]
    - name: Create caddy_config volume file
      ansible.builtin.copy:
        dest: /etc/containers/systemd/caddy_config.volume
        content: |
          [Volume]
    - name: Create container file
      ansible.builtin.copy:
        dest: /etc/containers/systemd/caddy.container
        content: |
          [Container]
          Image=docker.io/caddy
          Pull=always
          AutoUpdate=registry
          Network=caddy.network
          NetworkAlias=caddy
          Volume=/etc/caddy:/etc/caddy
          Volume=caddy_config.volume:/config
          Volume=caddy_data.volume:/data
          Notify=true

          [Service]
          Restart=always
          TimeoutStartSec=900

          [Install]
          WantedBy=default.target
    - name: Reload systemd daemon
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: Enable caddy socket
      ansible.builtin.systemd_service:
        name: caddy.socket
        enabled: true
        state: started
    - name: Restart caddy
      ansible.builtin.systemd_service:
        name: caddy.service
        state: restarted

